{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "zerotier-planet.namespace" . }}
  labels:
    {{- include "zerotier-planet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.existingSecretKey }}: {{ .Values.secret.ztncuiPassword | quote }}
{{- end }}
