apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs.fullname" . }}-tcp
  labels:
    {{- include "srs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "srs.selectorLabels" . | nindent 4 }}
  ports:
    - name: rtmp
      port: {{ .Values.service.tcp.rtmp }}
      targetPort: rtmp
      protocol: TCP
    - name: api
      port: {{ .Values.service.tcp.api }}
      targetPort: api
      protocol: TCP
    - name: http
      port: {{ .Values.service.tcp.http }}
      targetPort: http
      protocol: TCP